"""add product details

Revision ID: 43de94783c25
Revises: 
Create Date: 2026-04-28 09:35:16.598519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43de94783c25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ram', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('storage', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('display', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('battery', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('chip', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('charging', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('connectivity', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('connectivity')
        batch_op.drop_column('weight')
        batch_op.drop_column('charging')
        batch_op.drop_column('rating')
        batch_op.drop_column('type')
        batch_op.drop_column('chip')
        batch_op.drop_column('battery')
        batch_op.drop_column('display')
        batch_op.drop_column('storage')
        batch_op.drop_column('ram')
        batch_op.drop_column('processor')

    # ### end Alembic commands ###
