"""Initial migration

Revision ID: 56d739c04b8c
Revises: 
Create Date: 2026-03-27 09:06:53.413396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d739c04b8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_number', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_orders_reference_number', ['reference_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_reference_number', type_='unique')
        batch_op.drop_column('reference_number')

    # ### end Alembic commands ###
